# Generated by Django 2.2.3 on 2019-07-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('month', models.CharField(blank=True, max_length=255)),
                ('day', models.CharField(blank=True, max_length=255)),
                ('year', models.CharField(blank=True, max_length=255)),
                ('security_number1', models.CharField(blank=True, max_length=255)),
                ('security_number2', models.CharField(blank=True, max_length=255)),
                ('security_number3', models.CharField(blank=True, max_length=255)),
                ('citizenship', models.CharField(blank=True, max_length=255)),
                ('marital_status', models.CharField(blank=True, max_length=255)),
                ('no_of_dependents', models.CharField(blank=True, max_length=255)),
                ('investment_experience', models.CharField(blank=True, max_length=255)),
                ('employment_status', models.CharField(blank=True, max_length=255)),
                ('employee_name', models.CharField(blank=True, max_length=255)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('trade_options', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
